// locations.ts (create a separate file if you want reusability)
export const LOCATIONS = [
  "Southern Bypass",
  "E.M BYPASS",
  "Mukundapur",
  "OTHERS",
  "ELGIN ROAD",
  "SOUTHERN BYPASS",
  "JOKA",
  "TOLLYGUNGE",
  "Topsia",
  "Picnic Garden",
  "MOTILAL GUPTA ROAD",
  "RAJARHAT",
  "NEW ALIPORE",
  "B.L SAHA ROAD",
  "Jagatipota",
  "Kamalgazi",
  "KAKURGACHI",
  "RAJARHAT NEW TOWN",
  "DUNLOP",
  "MADHAYM GRAM",
  "NEWTOWN",
  "Hazra",
  "ROY BAHADUR ROAD BEHALA",
  "NEWTOWN ACTION AREA 1",
  "LAKETOWN",
  "EM Bypass",
  "Kalikapore",
  "Highland park",
  "JADAVPUR",
  "MUKUNDOPUR",
  "Golf Green",
  "ECO SPACE",
  "JODHPUR PARK",
  "Kasba",
  "purbalok",
  "Haltu",
  "Lake Gardens",
  "New Garia , Nayabad",
  "Rajarhat",
  "Camac street",
  "BIRATI",
  "Lataguri , Dooars",
  "HOWRAH",
  "BATANAGAR",
  "Newtown AA-3",
  "CHINAR PARK",
  "Action Area 3",
  "Madhyamgram",
  "Newtown AA-2",
  "Hindmotors",
  "ACTION AREA 2 NEW TOWN",
  "Newtown AA-1",
  "Tangra",
  "PRINCE ANWAR SHAH ROAD",
  "Mahishbatan",
  "Kalighat",
  "Santoshpur",
  "Madurdaha",
  "Gariahat",
  "ENTALLY",
  "Kalikapur Haltu",
  "Hussainpur",
  "Narendrapur Rajpur Sonarpur, Kolkata",
  "Manicktala Machuabazar",
  "Paschim Putiary",
  "kamalgachi",
  "Standalone",
  "Rash behari",
  "Saltlake",
  "Satragachi",
  "Domjur",
  "Mourigram Howrah",
  "New Garia",
  "Sarat bose Road",
  "New Town, Kolkata",
  "Nayabad",
  "Singur",
  "N S C Bose Road",
  "Jadubabur Bazar",
  "SERAMPORE - Hoogly",
  "Konnagar hoogly",
  "SOUTHEND PARK",
  "Haltu, Kolkata",
  "Naktala",
  "Shreebhumi",
  "Squareland Park",
  "KASBA",
  "Action Area II",
  "Rajdanga, Kolkata",
  "Rath Tala Kasba",
  "Action Area III",
  "Sarat Bose Rd",
  "Patuli",
  "Dhapa",
  "NSC BOSE ROAD",
  "Lake Town",
  "BASANTI HIGH WAY",
  "JABALPUR",
  "ADIPALLY, Kolkata",
  "KHUDIRAM METRO STATION",
  "BALLYGUNGE",
  "New Town AA2",
  "MOHISHBATHAN",
  "Samsara",
  "Off EM Bypass",
  "Eastern Metropolitan Bypass",
  "KASBA NEW MARKET",
  "Rash Behari Avenue",
  "Eastend Park",
  "Garia Hindustan More",
  "Saket Sadan",
  "Purba Para Bosepukur",
  "PS",
  "New Town AA1",
  "ANDUL",
  "SUBASHGRAM",
  "Alipore",
  "Godrej",
  "Behala",
  "Survey Park",
  "Bagha Jatin",
  "LAKE GARDEN",
  "Chanditala",
  "ROY BAHADUR ROAD",
  "Purbachal Haltu",
  "Near Acropolis Mall",
  "MINTO PARK",
  "Salt Lake Sector 1",
  "NSC BOSE",
  "KABARDANGA",
  "Beleghata",
  "Dum Dum",
  "KARUNAMOYEE",
  "BT ROAD",
  "Ruchi Realty",
  "RAMGHAR",
  "Siliguri",
  "Eastern Metropolitan Byp Rd",
  "Kankurgachi",
  "Mahamayatala",
];
