 const preferredConfigs = [
        '1 BHK',
        '1.5 BHK',
        '2 BHK',
        '2.5 BHK',
        '3 BHK',
        '3.5 BHK',
        '4 BHK',
        '4.5 BHK',
        '5 BHK',
        '5.5 BHK',
        '6 BHK',
        '6.5 BHK',
        '7 BHK',
        '7.5 BHK',
        '8 BHK',
        '8.5 BHK',
        '9 BHK',
        '9.5 BHK',
        '10 BHK',
        'Duplex',
        'Penthouse',
        'Villa',
        'Plot',
        'Suite',
        'Studio Apartment',
        'Commercial Space',
        'Office Space',
    ]

    export default preferredConfigs