export const STATUS_MAPPING: Record<string, { disposition: string; category: string }> = {
    "1st Try": { "disposition": "IN Progress", "category": "Retry" },
    "2nd try": { "disposition": "IN Progress", "category": "Retry" },
    "3rd try": { "disposition": "IN Progress", "category": "Retry" },
    "4th Try": { "disposition": "IN Progress", "category": "Retry" },
    "5th Try": { "disposition": "IN Progress", "category": "Retry" },
    "6th Try": { "disposition": "IN Progress", "category": "Retry" },
    "7th Try": { "disposition": "IN Progress", "category": "Retry" },
    "8th Try": { "disposition": "IN Progress", "category": "Retry" },
    "Call Back in Progress": { "disposition": "IN Progress", "category": "Retry" },
    "9th Try": { "disposition": "Unqualified", "category": "Junk" },
    "Call Back": { "disposition": "Follow Up", "category": "Cold" },
    "Follow Up for feedback": { "disposition": "Follow Up", "category": "Cold" },
    "Interested in the project": { "disposition": "Follow Up", "category": "Cold" },
    "No Answer/Number is busy": { "disposition": "Follow Up", "category": "Retry" },
    "SV Prospect": { "disposition": "Follow Up", "category": "Warm" },
    "Already Booked somewhere": { "disposition": "Unqualified", "category": "Junk" },
    "Bad Data": { "disposition": "Unqualified", "category": "Junk" },
    // "Booked with us": { "disposition": "Unqualified", "category": "Junk" },
    "Complaint Call": { "disposition": "Unqualified", "category": "Junk" },
    "Channel Partner": { "disposition": "Unqualified", "category": "Junk" },
    "Customer Stopped Responding": { "disposition": "Unqualified", "category": "Junk" },
    "Duplicate": { "disposition": "Unqualified", "category": "Junk" },
    "Flat Size Mismatch": { "disposition": "Unqualified", "category": "Junk" },
    "Flat Owner for Resale/Rental": { "disposition": "Unqualified", "category": "Junk" },
    "Requirement Mismatch": { "disposition": "Unqualified", "category": "Junk" },
    "Floor Mismatch": { "disposition": "Unqualified", "category": "Junk" },
    "For Upcoming Project": { "disposition": "Unqualified", "category": "Junk" },
    "General/Casual Enquiry": { "disposition": "Unqualified", "category": "Junk" },
    "Location Mismatch": { "disposition": "Unqualified", "category": "Junk" },
    "Non Contactable": { "disposition": "Unqualified", "category": "Junk" },
    "Not Interested": { "disposition": "Unqualified", "category": "Junk" },
    "No Requirement": { "disposition": "Unqualified", "category": "Junk" },
    "Out of Budget/Budget Mismatch": { "disposition": "Unqualified", "category": "Junk" },
    "Plan Postponed": { "disposition": "Unqualified", "category": "Junk" },
    "Possession Time Mismatch": { "disposition": "Unqualified", "category": "Junk" },
    "Test": { "disposition": "Unqualified", "category": "Junk" },
    "Will Call us back": { "disposition": "Unqualified", "category": "Cold" },
    "Wrong Number": { "disposition": "Unqualified", "category": "Junk" },
    "Interested in the Project": { "disposition": "SV Push", "category": "Cold" },
    "Call Back Needed": { "disposition": "SV Push", "category": "Cold" },
    "SV Appointed Fixed": { "disposition": "SV Push", "category": "Warm" },
    "Upcoming Project": { "disposition": "SV Push", "category": "Cold" },
    "Site Visit Done": { "disposition": "SV Push", "category": "Hot" },
    "Booked With Us": { "disposition": "SV Push", "category": "Hot" }
};